# cli: data-replicator configs/cross_metastore/uc_metadata_defaults.yaml --target-catalogs [catalog_name] --target-schemas [schema1,schema2] --uc-object-types [table_tag,column_tag]
# 1. Delta share is not required for uc replication. Both source and target UC should be accessible via Databricks Connect.
# 2. Replicate source UC metadata objects to target UC.
# 3. For external tables, use external location mapping specified below
# 4. No replication_wait_secs is needed as both source and target are UC.

version: "1.0"

replication_group: "uc_metadata"

storage_credential_config:
  target_credential_type: "aws"
  mapping:
    aarontest: "arn:aws:iam::332745928618:role/ad-s3-multi-region-demo"
    oneenv-adls: "arn:aws:iam::332745928618:role/ad-s3-multi-region-demo"

cloud_url_mapping:
  "abfss://aaboode@oneenvadls.dfs.core.windows.net/": "s3://one-env-uc-external-location/aaron2"

audit_config:
  audit_table: "data_replication.audit.audit_logging"

replication_config:
  enabled: true

concurrency:
  max_workers: 5
  timeout_seconds: 1800

retry:
  max_attempts: 3
  retry_delay_seconds: 10
